/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cc_clv_yamiHikariGame_gamecenter_GameCenter */

#ifndef _Included_cc_clv_yamiHikariGame_gamecenter_GameCenter
#define _Included_cc_clv_yamiHikariGame_gamecenter_GameCenter

extern "C" {

/*
 * Class:     cc_clv_yamiHikariGame_gamecenter_GameCenter
 * Method:    onSignInProcessCompleted
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_cc_clv_yamiHikariGame_gamecenter_GameCenter_onSignInProcessCompleted
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     cc_clv_yamiHikariGame_gamecenter_GameCenter
 * Method:    onSignOutProcessCompleted
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cc_clv_yamiHikariGame_gamecenter_GameCenter_onSignOutProcessCompleted
  (JNIEnv *, jclass);

}

#endif

