# encoding: utf-8

require 'yaml'
require 'json'
require 'plist'

RESOURCES_DIR = '../Resources'

task :default => "settings:dropItemSettings"

namespace "settings" do
  DROP_ITEM_SETTINGS_FILENAME = 'dropItems.plist'
  
  desc "generate #{DROP_ITEM_SETTINGS_FILENAME}"
  task :dropItemSettings do
    File.open(File.join(RESOURCES_DIR, DROP_ITEM_SETTINGS_FILENAME), "w") do |file|
      file << YAML.load_file('dropItems.yml').to_plist
    end
  end
end